// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using KooliProjekt.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260508231931_DataAnnotations")]
    partial class DataAnnotations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KooliProjekt.Application.Data.KaaluMootmine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Kaal")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("Kuupaev")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatsientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatsientId");

                    b.ToTable("KaaluMootmised");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Kasutaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Eesnimi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parool")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Perekonnanimi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Kasutajad");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Patsient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Eesnimi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Isikukood")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("KasutajaId")
                        .HasColumnType("int");

                    b.Property<string>("Perekonnanimi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Synniaeg")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KasutajaId");

                    b.ToTable("Patsiendid");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Soogikord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Kuupaev")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatsientId")
                        .HasColumnType("int");

                    b.Property<int>("Tyyp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatsientId");

                    b.ToTable("Soogikorrad");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.SoogikorraRida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Kogus")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("SoogikordId")
                        .HasColumnType("int");

                    b.Property<int>("ToiduaineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoogikordId");

                    b.HasIndex("ToiduaineId");

                    b.ToTable("SoogikorraRead");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToDoListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToDoListId");

                    b.ToTable("ToDoItems");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ToDoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Toiduaine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Energia")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Kiudained")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MillestKullastunud")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("MillestSuhkrud")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Nimetus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rasvad")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Sool")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Susivesikud")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("Valgud")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Toiduained");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.VererohuMootmine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Diastoolne")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Kellaaeg")
                        .HasColumnType("time");

                    b.Property<DateTime>("Kuupaev")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatsientId")
                        .HasColumnType("int");

                    b.Property<int>("Pulss")
                        .HasColumnType("int");

                    b.Property<int>("Sustoolne")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatsientId");

                    b.ToTable("VererohuMootmised");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.VeresuhkruMootmine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Kellaaeg")
                        .HasColumnType("time");

                    b.Property<DateTime>("Kuupaev")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatsientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Veresuhkur")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatsientId");

                    b.ToTable("VeresuhkruMootmised");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.KaaluMootmine", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Patsient", "Patsient")
                        .WithMany("KaaluMootmised")
                        .HasForeignKey("PatsientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patsient");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Patsient", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Kasutaja", "Kasutaja")
                        .WithMany("Patsiendid")
                        .HasForeignKey("KasutajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kasutaja");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Soogikord", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Patsient", "Patsient")
                        .WithMany("Soogikorrad")
                        .HasForeignKey("PatsientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patsient");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.SoogikorraRida", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Soogikord", "Soogikord")
                        .WithMany("Read")
                        .HasForeignKey("SoogikordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooliProjekt.Application.Data.Toiduaine", "Toiduaine")
                        .WithMany("SoogikorraRead")
                        .HasForeignKey("ToiduaineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soogikord");

                    b.Navigation("Toiduaine");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ToDoItem", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.ToDoList", "ToDoList")
                        .WithMany()
                        .HasForeignKey("ToDoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDoList");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.VererohuMootmine", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Patsient", "Patsient")
                        .WithMany("VererohuMootmised")
                        .HasForeignKey("PatsientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patsient");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.VeresuhkruMootmine", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Patsient", "Patsient")
                        .WithMany("VeresuhkruMootmised")
                        .HasForeignKey("PatsientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patsient");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Kasutaja", b =>
                {
                    b.Navigation("Patsiendid");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Patsient", b =>
                {
                    b.Navigation("KaaluMootmised");

                    b.Navigation("Soogikorrad");

                    b.Navigation("VererohuMootmised");

                    b.Navigation("VeresuhkruMootmised");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Soogikord", b =>
                {
                    b.Navigation("Read");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Toiduaine", b =>
                {
                    b.Navigation("SoogikorraRead");
                });
#pragma warning restore 612, 618
        }
    }
}
